"use client";

import { useMemo } from "react";
import { ArrowLeft, AlertTriangle, CheckCircle2, ClipboardList, Download, MessageSquare, Star } from "lucide-react";
import { AppShell } from "@/components/AppShell";
import { Button } from "@/components/Button";
import { useOperations } from "@/context/OperationsContext";
import { useEventLog } from "@/context/EventLogContext";
import { useRouter } from "next/navigation";

type SummaryCardProps = {
  icon: React.ReactNode;
  label: string;
  value: string;
  helper: string;
};

function SummaryCard({ icon, label, value, helper }: SummaryCardProps) {
  return (
    <div
      className="min-w-[150px] flex-1 rounded-lg border border-white/10 p-4 text-sm"
      style={{ background: "color-mix(in oklab, var(--panel), transparent 80%)" }}
    >
      <div className="flex items-center gap-2 text-[11px] uppercase tracking-wide" style={{ color: "color-mix(in oklab, var(--foreground), transparent 45%)" }}>
        <span className="text-brand">{icon}</span>
        {label}
      </div>
      <div className="mt-1 text-xl font-semibold" style={{ color: "var(--foreground)" }}>
        {value}
      </div>
      <div className="mt-1 text-[11px]" style={{ color: "color-mix(in oklab, var(--foreground), transparent 45%)" }}>
        {helper}
      </div>
    </div>
  );
}

function ReviewsAnalyticsContent() {
  const router = useRouter();
  const { followUps, tickets } = useOperations();
  const { events } = useEventLog();

  const openFollowUps = followUps.filter((item) => item.status === "open").length;
  const inProgressFollowUps = followUps.filter((item) => item.status === "in_progress").length;
  const snoozedFollowUps = followUps.filter((item) => item.status === "snoozed").length;
  const completedFollowUps = followUps.filter((item) => item.status === "completed").length;

  const activeTickets = tickets.filter((ticket) => ticket.status !== "completed").slice(0, 5);

  const operationsEvents = useMemo(
    () => events.filter((entry) => (entry.category as string) === "operations").slice(0, 8),
    [events]
  );

  const responseRate = followUps.length
    ? Math.round(((completedFollowUps + inProgressFollowUps) / followUps.length) * 100)
    : 0;

  const downloadStub = () => {
    alert("Review analytics export is on the roadmap. For now, copy data from the dashboard.");
  };

  return (
    <div className="space-y-6">
      <div className="flex flex-wrap items-center justify-between gap-3">
        <Button
          variant="ghost"
          size="sm"
          onClick={() => router.push("/reviews")}
          className="inline-flex items-center gap-2 text-xs uppercase tracking-[0.2em]"
        >
          <ArrowLeft size={14} />
          Back to reviews
        </Button>
        <div className="inline-flex items-center gap-2">
          <Button size="sm" variant="secondary" className="inline-flex items-center gap-2" onClick={downloadStub}>
            <Download size={14} />
            Download report
          </Button>
        </div>
      </div>

      <div>
        <h1 className="text-2xl font-semibold" style={{ color: "var(--foreground)" }}>
          Review Intelligence
        </h1>
        <p className="mt-1 max-w-2xl text-sm" style={{ color: "color-mix(in oklab, var(--foreground), transparent 45%)" }}>
          Monitor follow-up velocity, agent workflow, and operational tickets generated by the review agent.
        </p>
      </div>

      <div className="flex flex-wrap gap-3">
        <SummaryCard
          icon={<Star size={16} />}
          label="Follow-ups"
          value={`${followUps.length}`}
          helper={`${openFollowUps} open • ${completedFollowUps} completed`}
        />
        <SummaryCard
          icon={<CheckCircle2 size={16} />}
          label="Response coverage"
          value={`${responseRate}%`}
          helper="Share of follow-ups closed or in motion"
        />
        <SummaryCard
          icon={<MessageSquare size={16} />}
          label="Ops Tickets"
          value={`${tickets.length}`}
          helper="Active & historical requests"
        />
        <SummaryCard
          icon={<AlertTriangle size={16} className="text-amber-300" />}
          label="Snoozed"
          value={`${snoozedFollowUps}`}
          helper="Waiting on customer updates"
        />
      </div>

      <div className="grid gap-4 lg:grid-cols-[minmax(0,2.5fr)_minmax(0,1.5fr)]">
        <div className="rounded-xl border border-white/10 bg-white/5 p-4" style={{ background: "color-mix(in oklab, var(--panel), transparent 85%)" }}>
          <div className="flex items-center justify-between">
            <h2 className="text-sm font-semibold" style={{ color: "var(--foreground)" }}>
              Follow-up pipeline
            </h2>
            <span className="text-[11px] uppercase tracking-[0.25em]" style={{ color: "color-mix(in oklab, var(--foreground), transparent 60%)" }}>
              {followUps.length} records
            </span>
          </div>
          <div className="mt-3 space-y-3 text-xs" style={{ color: "color-mix(in oklab, var(--foreground), transparent 55%)" }}>
            {followUps.length === 0 ? (
              <div className="rounded-lg border border-white/10 bg-white/5 p-4 text-center text-[11px]">
                No follow-ups scheduled yet. Queue activity from the reviews page to see workflow here.
              </div>
            ) : (
              followUps.map((item) => (
                <div key={item.id} className="rounded-lg border border-white/10 bg-white/5 p-3">
                  <div className="flex flex-wrap items-center justify-between gap-2">
                    <div className="space-y-1">
                      <div className="flex items-center gap-2 text-sm font-semibold" style={{ color: "var(--foreground)" }}>
                        {item.contactName}
                        {item.company ? (
                          <span className="text-xs font-medium" style={{ color: "color-mix(in oklab, var(--foreground), transparent 55%)" }}>
                            • {item.company}
                          </span>
                        ) : null}
                      </div>
                      <div className="text-[11px]" style={{ color: "color-mix(in oklab, var(--foreground), transparent 55%)" }}>
                        {item.reason === "missed_call" ? "Missed receptionist call" : item.reason === "idle" ? "Dormant relationship" : "Custom follow-up"}
                      </div>
                    </div>
                    <span
                      className="inline-flex items-center gap-2 rounded-full px-3 py-1 text-[11px] font-semibold uppercase tracking-wide"
                      style={{
                        background: "color-mix(in oklab, var(--panel), transparent 70%)",
                        color: "color-mix(in oklab, var(--foreground), transparent 20%)",
                        border: "1px solid color-mix(in oklab, var(--ring), transparent 40%)",
                      }}
                    >
                      {item.status.replace("_", " ")}
                    </span>
                  </div>
                  <div className="mt-2 flex flex-wrap items-center gap-3 text-[11px]" style={{ color: "color-mix(in oklab, var(--foreground), transparent 55%)" }}>
                    <span>Value • £{item.annualValueGBP.toLocaleString()}</span>
                    <span>Last touch • {new Date(item.lastTouchpoint).toLocaleDateString("en-GB")}</span>
                    {item.assignedTo ? <span>Owner • {item.assignedTo}</span> : <span>Unassigned</span>}
                    {item.snoozedUntil ? <span>Snoozed until {new Date(item.snoozedUntil).toLocaleString("en-GB")}</span> : null}
                  </div>
                </div>
              ))
            )}
          </div>
        </div>

        <div className="space-y-4">
          <div className="rounded-xl border border-white/10 bg-white/5 p-4" style={{ background: "color-mix(in oklab, var(--panel), transparent 88%)" }}>
            <div className="flex items-center justify-between">
              <h2 className="text-sm font-semibold" style={{ color: "var(--foreground)" }}>
                Active ops tickets
              </h2>
              <Button variant="ghost" size="sm" onClick={() => router.push("/settings")} className="text-xs">
                View all
              </Button>
            </div>
            <div className="mt-3 space-y-3 text-xs" style={{ color: "color-mix(in oklab, var(--foreground), transparent 55%)" }}>
              {activeTickets.length === 0 ? (
                <div className="rounded-lg border border-white/10 bg-white/5 p-4 text-center text-[11px]">
                  No open tickets. Queue a configuration request from the workflows or reviews pages.
                </div>
              ) : (
                activeTickets.map((ticket) => (
                  <div key={ticket.id} className="rounded-lg border border-white/10 bg-white/5 p-3">
                    <div className="flex flex-wrap items-center justify-between gap-2">
                      <span className="text-sm font-semibold" style={{ color: "var(--foreground)" }}>
                        {ticket.subject}
                      </span>
                      <span className="text-[10px]" style={{ color: "color-mix(in oklab, var(--foreground), transparent 60%)" }}>
                        Owner • {ticket.owner}
                      </span>
                    </div>
                    <div className="mt-1 text-[11px]" style={{ color: "color-mix(in oklab, var(--foreground), transparent 55%)" }}>
                      {ticket.summary}
                    </div>
                  </div>
                ))
              )}
            </div>
          </div>

          <div className="rounded-xl border border-white/10 bg-white/5 p-4" style={{ background: "color-mix(in oklab, var(--panel), transparent 90%)" }}>
            <div className="flex items-center justify-between">
              <h2 className="text-sm font-semibold" style={{ color: "var(--foreground)" }}>
                Event log
              </h2>
              <div className="text-[11px]" style={{ color: "color-mix(in oklab, var(--foreground), transparent 60%)" }}>
                {operationsEvents.length} entries
              </div>
            </div>
            <div className="mt-3 space-y-2 text-[11px]" style={{ color: "color-mix(in oklab, var(--foreground), transparent 55%)" }}>
              {operationsEvents.length === 0 ? (
                <div className="rounded-lg border border-white/10 bg-white/5 p-3 text-center">
                  No operational events recorded yet.
                </div>
              ) : (
                operationsEvents.map((event) => (
                  <div key={event.id} className="rounded-lg border border-white/10 bg-white/5 p-3">
                    <div className="flex flex-wrap items-center justify-between gap-2">
                      <span className="text-sm font-semibold" style={{ color: "var(--foreground)" }}>
                        {event.summary}
                      </span>
                      <span style={{ color: "color-mix(in oklab, var(--foreground), transparent 60%)" }}>
                        {new Date(event.createdAt).toLocaleString("en-GB", {
                          day: "numeric",
                          month: "short",
                          hour: "2-digit",
                          minute: "2-digit",
                        })}
                      </span>
                    </div>
                    {event.meta ? (
                      <pre className="mt-2 rounded bg-black/20 p-2 text-[10px]" style={{ color: "color-mix(in oklab, var(--foreground), transparent 65%)" }}>
                        {JSON.stringify(event.meta, null, 2)}
                      </pre>
                    ) : null}
                  </div>
                ))
              )}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

export default function ReviewsAnalyticsPage() {
  return (
    <AppShell>
      <ReviewsAnalyticsContent />
    </AppShell>
  );
}

